#!/usr/bin/env python3
# Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0
"""Generate frontend/src/game/rte7000Presets.ts from the RTE7000 France THT
graded scenario database (data/rte7000_tht/scenarios.json).

The generated module embeds the graded scenarios as player-safe `GameStudy`
objects (NO reference `solution` — that stays server-side in scenarios.json),
grouped into easy / medium / hard tiers, plus a deterministic `sampleRte7000`
helper so the UI can draw N scenarios of a chosen difficulty.

Run after (re)building scenarios.json:
    python3 scripts/game_mode/gen_rte7000_presets.py
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB = os.path.join(REPO, "data", "rte7000_tht", "scenarios.json")
OUT = os.path.join(REPO, "frontend", "src", "game", "rte7000Presets.ts")

HEADER = """// Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
// SPDX-License-Identifier: MPL-2.0
//
// AUTO-GENERATED by scripts/game_mode/gen_rte7000_presets.py from
// data/rte7000_tht/scenarios.json. Do not edit by hand.
//
// RTE7000 France THT game mode: difficulty-graded N-1 scenarios on reconstructed
// real French THT (>=200 kV) operating points. Difficulty is the expert
// recommender's solvability at the 95% monitoring factor:
//   easy   - a suggested unitary action resolves the overloads;
//   medium - no unitary resolves, but a first-identified combination does;
//   hard   - neither a unitary nor a first combination resolves.
// Dates are hidden: titles carry only month + weekday + hour-period, and grids
// live under opaque ids. Non-antenna scenarios only.

import type { GameStudy } from './types';

export type Rte7000Difficulty = 'easy' | 'medium' | 'hard';

export interface Rte7000Tier {
  id: Rte7000Difficulty;
  label: string;
  blurb: string;
  studies: GameStudy[];
}
"""

FOOTER = """
export const RTE7000_TIERS: Rte7000Tier[] = [
  { id: 'easy',   label: 'Easy — RTE7000 France THT',
    blurb: 'A single suggested action clears the overload (expert model, 95% monitoring).',
    studies: RTE7000_EASY },
  { id: 'medium', label: 'Medium — RTE7000 France THT',
    blurb: 'No single action suffices, but a first-identified pair does.',
    studies: RTE7000_MEDIUM },
  { id: 'hard',   label: 'Hard — RTE7000 France THT',
    blurb: 'Neither a single action nor the best estimated pairs resolve it.',
    studies: RTE7000_HARD },
];

const BY_DIFFICULTY: Record<Rte7000Difficulty, GameStudy[]> = {
  easy: RTE7000_EASY, medium: RTE7000_MEDIUM, hard: RTE7000_HARD,
};

// Deterministic (seedable) sampler: draw up to `n` scenarios of a difficulty,
// round-robin across distinct grids first so a small sample spans different
// operating points. `seed` omitted → non-deterministic draw.
export function sampleRte7000(
  difficulty: Rte7000Difficulty, n: number, seed?: number,
): GameStudy[] {
  const pool = [...(BY_DIFFICULTY[difficulty] ?? [])];
  let s = (seed ?? Math.floor(Math.random() * 2 ** 31)) >>> 0;
  const rnd = () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; };
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1)); [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const byGrid = new Map<string, GameStudy[]>();
  for (const st of pool) {
    const g = st.networkPath;
    if (!byGrid.has(g)) byGrid.set(g, []);
    byGrid.get(g)!.push(st);
  }
  const groups = [...byGrid.values()];
  const ordered: GameStudy[] = [];
  while (groups.some((g) => g.length)) {
    for (const g of groups) { const st = g.pop(); if (st) ordered.push(st); }
  }
  return ordered.slice(0, n);
}
"""


def to_study(s):
    return {
        "id": s["id"],
        "label": s["label"],
        "networkPath": s["networkPath"],
        "actionFilePath": s["actionFilePath"],
        "contingencyElementId": s["contingencyElementId"],
        "contingencyLabel": s.get("contingencyLabel"),
        "baselineMaxLoadingPct": s.get("baselineMaxLoadingPct"),
        "description": (f"{s['title']}. Loss of {s['contingencyLabel']} drives a worst-case "
                        f"{s.get('baselineMaxLoadingPct')}% line loading. Bring every monitored "
                        f"line back under the 95% monitoring limit."),
    }


def main():
    db = json.load(open(DB, encoding="utf-8"))
    buckets = {"easy": [], "medium": [], "hard": []}
    for s in db["scenarios"]:
        if s["difficulty"] in buckets:
            buckets[s["difficulty"]].append(to_study(s))
    lines = [HEADER]
    for diff, const in (("easy", "RTE7000_EASY"), ("medium", "RTE7000_MEDIUM"), ("hard", "RTE7000_HARD")):
        arr = json.dumps(buckets[diff], indent=2, ensure_ascii=False)
        lines.append(f"\nexport const {const}: GameStudy[] = {arr};")
    lines.append(FOOTER)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: easy={len(buckets['easy'])} medium={len(buckets['medium'])} "
          f"hard={len(buckets['hard'])}")


if __name__ == "__main__":
    main()
